services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 5Tor0ngPas5w0rD
      POSTGRES_DB: mydb
    ports:
      - "${PORTDATABASE}:5432"
    env_file:
      - .env 
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_data: